<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RestartBtn</name>
   <tag></tag>
   <elementGuidId>3b1ca47c-3ee3-4b15-85a8-b8d690780d16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[text()=&quot;Restart&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.resetBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Restart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2989cf73-b5ca-47d3-9ef3-82fe0531a54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resetBtn</value>
      <webElementGuid>ee1fd25c-df08-4025-aec4-495ae099c417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/1to50/en/</value>
      <webElementGuid>0a6e437d-d1d2-447b-9259-aefb402fc3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Restart</value>
      <webElementGuid>71778aea-dd02-4876-b8d7-8c1a99da9d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wrap&quot;]/div[@class=&quot;stage&quot;]/div[@class=&quot;lineWrapB&quot;]/div[@class=&quot;description&quot;]/a[@class=&quot;resetBtn&quot;]</value>
      <webElementGuid>840d25f1-16ae-4658-ad82-f359cc5f97c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Restart')]</value>
      <webElementGuid>f2d61b9a-9a2c-4786-89e3-5284b5c16e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST COMPLETED'])[1]/following::a[1]</value>
      <webElementGuid>5d3a88f2-367f-46f9-9abd-d8724ea32a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='광고'])[1]/preceding::a[1]</value>
      <webElementGuid>7f7a9849-00e8-40d9-b66e-8b80889a813d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Restart']/parent::*</value>
      <webElementGuid>428c00e9-26e8-45a1-886a-aaa0ee2cf8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/1to50/en/')]</value>
      <webElementGuid>58fec420-84a3-4830-b78f-ac3b68cc9178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>7f2d392b-46fb-467f-9a8b-5d8e4b32226a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/1to50/en/' and (text() = 'Restart' or . = 'Restart')]</value>
      <webElementGuid>2543ed65-33f0-422c-a9fe-bf3cfd9eda7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
